parameters:
    remember_me_lifetime: 2592000 # 30 days in seconds

security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            provider: user_provider
            logout:
                path: logout
                target: homepage
            remember_me:
                httponly: false
                lifetime: '%remember_me_lifetime%'
                name: SHINNYREMEMBERME
                samesite: strict
                secret: '%kernel.secret%'
                secure: true
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
