twig:
    exception_controller: ~
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        brand_name: '%brand_name%'
        remember_me_lifetime: '%remember_me_lifetime%'